### ISSUE TITLE
2.08 OSX Release?

### ISSUE THREAD

**Issue by jonn26** [buddhi1980/mandelbulber2#102]
I noticed there is not an OSX dmg file release with the new 2.08  / 2.08-1 version. Are you still supporting OSX?

**Comment by zebastian** [comment]
The OSX build is passing, so we will be able to provide one. However we dont have it present yet, since the new version was just released.
Hopefully in the next couple of days you can get a new version.
If you are feeling curious you can also build yourself. see here for instructions:
https://github.com/buddhi1980/mandelbulber2/blob/master/mandelbulber2/deploy/README-osx.txt
If you go this way, we would appreciate any feedback.

**Comment by jonn26** [comment]
Ah, ok gtk. Will most likely wait for the release unless I get some free time.

Thanks for all the hard work, can't wait to try the new texture features : )
