### ISSUE TITLE
Rearrange saving of images (selection of image format)

### ISSUE THREAD

**Issue by buddhi1980** [buddhi1980/mandelbulber2#103]
Selection of image format should be done in FileDialog instead of pull down menu or preferences dialog. This will make it simpler for users

**Comment by mclarekin** [comment]
H'mmm

The pull down menu is fast,

Generally in software in preferences we *set* preferences, in drop down
menu we *use*  prefernces.

Can not tell you any more because this crazy ubuntu has just lost all the
menu names in all programs, so all I see is icons on drop down menus.
Aghhh!!!  I need to reboot ubuntu

On Sun, Jul 10, 2016 at 2:32 AM, Krzysztof Marczak <notifications@github.com
