### ISSUE TITLE
Images have a border

### ISSUE THREAD

**Issue by capn-damo** [buddhi1980/mandelbulber2#126]
Mandelbulber version: 2.08-3; compiled for both Debian Jessie and UbuntuStudio.

Image displayed in the Mandelbulber image window, and saved images, show a border of a few px. This needs to be cropped out after exporting.

**Comment by buddhi1980** [comment]
I cannot see any border. Is this happens always? Which format do you use to save images? What color of border do you see? Could you upload any image which has this border?

**Comment by capn-damo** [comment]
Screenshot of MB2 render window, on top of 3840x2160 rendered png. There is a 8px wide paler gradient border showing.
(A 1600x1200 image shows a 4px border)

![mb-scrot-2](https://cloud.githubusercontent.com/assets/11060704/17712609/b1ecf25c-63ee-11e6-9d0b-1a5e6be2be27.png)

I haven't investigated if it happens with all formulae, but I have noticed it with every one I have done so far.

**Comment by buddhi1980** [comment]
This is a side effect of Screen Space Ambient Occlusion (SSAO). This effect is a post effect based on z-buffer. Because on the border of image there is lack of data, the brightness can be wrong. To reduce size and visibility of the border you can increase quality of effect (Effects / Ambient occlusion / Quality) or use another type of Ambient Occlusion effect.

**Comment by capn-damo** [comment]
OK. Thanks for the quick clarification - I will bear it in mind in the future :)

**Comment by mclarekin** [comment]
Thanks Damo and Buddhi, I had noticed this sometime ago and forgotten about
it  It is good to understand what causes it and  how to address it..
