### ISSUE TITLE
Export Voxels using ISO 10303 STEP File Format

### ISSUE THREAD

**Issue by mancoast** [buddhi1980/mandelbulber2#156]
https://github.com/stepcode/stepcode/blob/master/COPYING

**Comment by mancoast** [comment]
https://github.com/buddhi1980/mandelbulber2/issues/151

**Comment by zebastian** [comment]
@mancoast and others:
Do we still want the STEP support, since we already got ply support by sadaszew.
On the other hand it shouldn't be too hard to make STEP support now, since the differences to PLY should not be that big.

What do you think?

**Comment by mancoast** [comment]
Greetings,

@zebastian, In my opinion, we should consider added value of STEP ISO 10303.
The primary advantage of STEP files would be 3D printer and engineering tool-set interoperation support.
STEP ISO 10303 is very generic file formart in plain-text with wide-spread support throughout engineering community.
I really want to load up fractals in SolidWorks, PRO-E, Autodesk, etc... and 3D print!

thanks,
coast

**Comment by mancoast** [comment]
Please provide hint/instructions.  Thanks!

**Comment by zebastian** [comment]
Since it is also a mesh-export it can be combined with the existing mesh exporter:
in
qt/mesh_export_dialog.cpp, qt/mesh_export_dialog.h, qt/mesh_export_dialog.ui
is the ui, there we need another toggle radio box -->
[ ] ply [x] step
also the wording of some fields have to be adopted

in the class src/mesh_export.cpp src/mesh_export.hpp there needs to be added the separation for ply / step as well. the underlying marching cubes algorithm does not need to be touched.
look for the line 
f.write(QString("ply\n").toLatin1());
this indicates the start of writing the results into the ply file. In regards to this implementation and the documentation of the STEP format you should e able to write the correct file.

**Comment by mancoast** [comment]
STEP ISO 10303 required for SolidWorks Rapid Prototype.
REF: https://www.sculpteo.com/en/tutorial/prepare-your-model-3d-printing-solidworks/

**Comment by zebastian** [comment]
@mancoast is this still a thing / Do we want this feature?
I can help you with that, but i cannot any proper documentation / tutorial of how to write a polygon model in this format...

**Comment by mancoast** [comment]
Ply is good, we can close

**Comment by zebastian** [comment]
Alright
