### ISSUE TITLE
Visual Studio Build "Not valid Mandelbulber settings file"

### ISSUE THREAD

**Issue by mancoast** [buddhi1980/mandelbulber2#212]
![image](https://cloud.githubusercontent.com/assets/7040493/22272659/6573d81a-e269-11e6-9bb4-dfcd3778a8d0.png)

I am thinking this might be related to new lines.
Any thoughts?

**Comment by buddhi1980** [comment]
How you got this error?

**Comment by mclarekin** [comment]
Grammar check = How did you get this error?

On Wed, Jan 25, 2017 at 6:01 PM, Krzysztof Marczak <notifications@github.com

**Comment by mancoast** [comment]
Greetings,

I receive this error on Application Entry during startup about (15) times.
I also get this error (1) once when trying to load settings from file.
In the latest build, the settings do not load from disk.
I have to copy settings to clipboard, then load from clipboard.
This should be tested/fixed if we want to release Visual Studio Binaries with xcompiled bins.
Build-Packages for the Visual Studio Binaries are on Appveyor as artifacts.

Thanks,
coast

**Comment by buddhi1980** [comment]
I will check what is wrong here

**Comment by buddhi1980** [comment]
I have found where is the problem. When there is used windows version of git tool, then all text files (including *.fract) are converted to Windows/DOS format with CR/LF line breaks. Linux format uses only CR. 
I haven't encountered this problem before, because I always works under Linux and all files created with Mandelbulber uses Linux format for text files (also under Windows). 
I need to modify cSettings class to be capable to load text files with CR/LF

**Comment by mancoast** [comment]
Muchos Gracias!

The Build-Package for Win32 should now include proper QT Deps given https://github.com/buddhi1980/mandelbulber2/commit/891b8a486567e0f3274dfe70a4ab3ecb4e6c2156

**Comment by buddhi1980** [comment]
Fixed. Now it will handle Linux-like and Windows-like text files with settings.

**Comment by mancoast** [comment]
Thanks!
