### ISSUE TITLE
INTEGRATE: 3D Printing into Mandelbulber software platform

### ISSUE THREAD

**Issue by mancoast** [buddhi1980/mandelbulber2#247]
I would like to modify the voxel export data to include Computer Aided Manufacturing Validation.
We can use online services, or c/c++ library. @buddhi1980 any thoughts?

**Comment by buddhi1980** [comment]
What you exactly mean? Is this about some specific data format?

**Comment by mancoast** [comment]
Picture this if you will:

We have just exported voxels from amazing 2D images.
Then we load up the data into our favorite CAD software.
Then we goto FILE->Print 3D.
We get 10,000 error messages about how the data is not printable.
In reality, a very small subset of designs can actually be manufactured.
We require a scan for this with Mandelbulber before exporting the voxels.

**Comment by buddhi1980** [comment]
So as I understand this is the software which validates cloud points if they are correct for 3D printing. Am I correct? Is it a check if data contain isolated voxels or too thin layers?

**Comment by mancoast** [comment]
@buddhi1980 Your understanding of Issue/Opportunity is absolutely correct!

True integration of 3D Printing into Mandelbulber software platform requires validation of cloud points for 3D-Printer Hardware.  Some software can automatically 'HEAL' cloud points for 3D-Printer Hardware.  

We can identify an API that provides 'VALIDATE' and 'HEAL' that operates on ISO 10303 STEP File Format  https://github.com/buddhi1980/mandelbulber2/issues/156.

**Comment by zebastian** [comment]
this topic is a huge field, there are already programs like meshlab and FIJI which can be used to manipulate 3d voxels in more ways than we could ever incorporate. Instead of reimplementing things already present in other software we should focus more on core features which mandelbulber still lacks. So i would say where the voxel rendering happens is where mandelbulber ends and a new software in a toolchain starts.
If we can find an easy way to integrate this anyway we could do it, but the time we are doing this, we cannot work on other places, which are more fundamental to the project.

About integrating 3rd party API:
probable technical problems:
- files are huge, upload to service may take long time
- API may be subject to change, so this may break in the future
- maybe not for free to use
- maybe service gets abandoned in the future
- may not be easily scriptable (user needs to customize paramaeters how the model has to be handled)
- different claims require different handling (user wants smooth surface , raw surface, internal geometry, without internal geometry, fixed holes, open holes, ....)

In general i am more into:
give good tutorials / info to the user how to after process voxel slices, than incorporating software to do this.

**Comment by mancoast** [comment]
Your input is valuable @zebastian.  We can table this issue for later and perhaps establish another project for 3D Printer Operations given our feature backlog shrinks.  I believe that we can reach a new audience of engineers.  Engineers tend to tinker and find/fix bugs.  This opportunity offers another use case scenario for download of Mandelbulber Software Platform for use on Engineering Systems.  I aim to implement all the requirements for this opportunity using SOLIDWORKS Native C++ API.  We then make this an attraction for additional talent.

**Comment by mancoast** [comment]
Mandelbulber Software Platform requires SOLIDWORKS Native C++ API [Unmanaged_CPP]
SOLIDWORKS provides 'state of art' automatic 'HEAL' of data sets for 3D-Printer Hardware.
REFERENCE: http://help.solidworks.com/2017/English/api/sldworksapiprogguide/Overview/Unmanaged_CPP_and_CPP_CLI_Code_Differences.htm
