### ISSUE TITLE
Feature: implementing compression in NetRender

### ISSUE THREAD

**Issue by acidhunter** [buddhi1980/mandelbulber2#256]
Hello there,

after getting mbulber running on many nodes (armhf/aarch64/i486/amd64) i tried to connect them to a client on a 100mbit line.

netrender was limited now by network speed.

After a very great talk to Krzysztof he asked me to open this issue here to share the details that i had discovered.

As a part of my job i do trys to compress the traffic between 2 offices with opensource technologies.

lzop & bortli does a very great job with a good compression ratio at a low cpu usage
comparsion:
https://lyncd.com/2015/09/lossless-compression-innovation/

https://catchchallenger.first-world.info/wiki/Quick_Benchmark:_Gzip_vs_Bzip2_vs_LZMA_vs_XZ_vs_LZ4_vs_LZO

https://github.com/google/brotli

implementing compression into the netrender engine will do a great effort when distributing to many nodes via WAN

**Comment by zebastian** [comment]
Hi Martin,

we have tried adding compression before with qCompress:
doc.qt.io/qt-4.8/qbyAtearray.html#qCompress which uses zlib internally
This works fine and has the desired behaviour. However this may make the server to the bottleneck, usercase: one thin server, which is only a collector for the rendered lines, multiple strong clients. Here the server may be too slow to uncompress the data in time.
Since we figured, that in most cases the network is locally for the client server architecture and the bandwidth is high, it is better to sacrifice bandwidth, than cpu power for compression / uncompression. This is why there is no compression happening at the moment.

But in your case it may be benificial to make this possible.

@buddhi1980 what do you think about following suggestion:
client has new 
	par->addParam("netrender_client_compression", false, morphNone, paramApp);
which is selectable in client tab, so if a client decides to better compress, he just sets this to true.
Instead of 
netCommand::netRender_DATA
he sends a new:
netCommand::netRender_DATA_COMPRESSED
and compresses the payload
the server knows to uncompress those netCommand::netRender_DATA_COMPRESSED
packages.
Drawback: This breaks backwards compatibility with old servers, so we need to make a mayor version bump. What do you think?

**Comment by buddhi1980** [comment]
There idea here is to use lzop compression which is way faster than zip

**Comment by mancoast** [comment]
Greetings!

Please upload the fractal settings file used for testing network bottleneck scenario.
I would like to recreate using my systems.

100mbit pipeline bandwidth utilitzation at 100% requires a huge render.
I am interested to see how mbulber does in my local labs.

Thanks!

**Comment by zebastian** [comment]
@buddhi1980 got carried away with the idea :)
zip was nice, since it is already built in, but by now we are familiar with adding new libraries.
zip has a good decompression speed (vs poor compression speed, but this is happening on the client mostly)
some hard numbers on a mandelbulber setup with different compression algorithms would be good.

**Comment by mancoast** [comment]
Any suggestions for prioritization of this new feature?  The added value of compression reduces requirements for server bandwidth.

**Comment by zebastian** [comment]
I am doing a couple of Tests right now comparing:
- Lzma
- ZIP
- No compression
I will post results in the next days...

**Comment by acidhunter** [comment]
i found this tool to benchmark and compare the various libs
https://github.com/inikep/lzbench

greets ;-)

**Comment by zebastian** [comment]
compression is already in place:
https://github.com/buddhi1980/mandelbulber2/blob/master/mandelbulber2/src/lzo_compression.h
this is using lzo1x_1_compress(...)
lzo1x 1 has a great (de-)compression speed, good compression ratio and was fairly easy to integrate.

**Comment by buddhi1980** [comment]
Tested under Windows 10 (mingw64 cross-compiled) - works very well. Cross compile scripts already corrected.

**Comment by buddhi1980** [comment]
Tested NetRender between two different platforms: Win10 <-> Debian - works OK.

**Comment by zebastian** [comment]
Nice, programming blindfolded :D
