### ISSUE TITLE
Difference Between Ray Marching and Ray Tracing, possible to substitute?

### ISSUE THREAD

**Issue by mancoast** [buddhi1980/mandelbulber2#287]
@buddhi1980  What are the chances of using Embree with this system?
https://embree.github.io/

**Comment by buddhi1980** [comment]
No chance. This kind of kernels are not optimized for fractals which are calculated from algorithms (no geometry data is available). This was the reason to write own rendering kernel.

**Comment by mancoast** [comment]
I seek the difference between "Ray Marching" and "Ray Tracing".
I understand Ray of light similar to how we see them coming down through the clouds from the sun.
That is pretty much the extent of my understanding of the algorithm, (I do not understand ray trace/march).

What is the difference?
Do we say Ray Marching, but actually mean Ray Tracing?

Where in the code exists the actual 'ray march'?

**Comment by buddhi1980** [comment]
here is good explanation what is ray-marching:
https://computergraphics.stackexchange.com/questions/161/what-is-ray-marching-is-sphere-tracing-the-same-thing

2017-04-20 22:27 GMT+02:00 mancoast <notifications@github.com>:

**Comment by taurus66** [comment]
In simple words (I try) raytracing is used, when a triangular geometry is used for objects. There is no step width for rayracing programs. a single ray measures the distance between camera and geometry, as the distance is given from the beginning. In distance estimated fractals the distance must be calculated step by step until the distance between raystep and surface is close enough to terminate calculation. Hope that helps.

**Comment by mancoast** [comment]
Thanks for info dudes.

So in my own words:
Ray-Tracing: requires **3D models** to render voxels.  
Ray-Marching: requires **formulas** to render voxels.  

We use algorithmic distance estimation with Ray-Marching to emulate light.
Please help me understand more regarding this distance estimation requirement.

Thanks!
coast

**Comment by buddhi1980** [comment]
Mandelbulber is not calculating voxels at all. It just calculate estimated distance to the objects.

**Comment by buddhi1980** [comment]
About distance estimation read our user manual. There is section about distance estimation.

**Comment by mancoast** [comment]
Actually, I aim to rewrite that segment of the manual. We need to confirm that my understanding is correct

**Comment by buddhi1980** [comment]
Why are you going to rewrite it, when you don't understand distance estimation and ray-marching? Are you  sure about it?

**Comment by mancoast** [comment]
The end user manual is for amateurs to the algorithm, such as myself. I feel that this enables me to explain it in a manner that can be understood by a broader audience of scientists, engineers, and hobbyists.  Realistically, we will benefit from a zero asumption approach that is precise and brief.  I need support to fully follow through on the manual improvements, which is why these questions and answers are interesting. 
Thanks, coast

**Comment by buddhi1980** [comment]
I will try to answer all your questions. Don't hesitate to ask.

**Comment by mancoast** [comment]
Thanks! I think the basic starting point is a ray of light. 
Everyone can envision the light through sky on a cloudy day. 
Another interesting example is the Ray of light we can see when we dive under water on a sunny day. 
From there we will explore.

**Comment by buddhi1980** [comment]
You have be careful which this kind of analogies, because in ray-marching programs, the light particles are going from eye to object, and from object to the light source.

**Comment by mclarekin** [comment]
It is confusing and I am still learning.

I don't think the term  ray tracing should be used anywhere.

This is how I think it works:

The formula creates an object.

For each pixel of our chosen resolution,  we create a vector from the
camera with a direction based on the geometry of the  Field Of View.

We use ray marching along these vectors, as a fast way to find a close
approximation of the  object position  in respect to the camera,

We march along the vector until we either get within tolerance (detail
size) or we determine that there is no object along that vector.

We now have a close approximation of the object on that vector  (i.e. a
point within tolerance to the object.)

We can then create a vector from the point to the light source and create
such things as shadows.

Using distance estimation we speed up the ray marching by having an
estimate of where the object is, and can then start checking the tolerance
from a location along the vector that is in theory near  to the object.

In the default situation  the tolerance (detail size) is smaller closer to
the camera, and larger in the distance. Using the Constant Detail Size
option we can make the Detail Size uniform at the cost of a slower render
time due to the extra ray marching iterations.





On Mon, Apr 24, 2017 at 6:45 AM, Krzysztof Marczak <notifications@github.com

**Comment by mclarekin** [comment]
This is my current understanding of the process.  I ignore complex numbers
( I think that section needs some fixing/clarification, TODO later):

Our 3D world begins as an infinite 3D grid of parallel positive and
negative integer points centered at the origin (0, 0, 0) in the complex
plane C.  An infinite "domain" I think??

I am not sure how the domain is then restricted (closed)  so that we do not
bother to test points that are located out towards infinity.

One method is to only iterate points within a domain bounded by a sphere or
a cube. ??????

These original points are  defined as generic vector C. Unfortunately I
used the term c pixel, but in retrospect I  would prefer "pixel" to be used
only when talking about image resolution and ray marching

Then using a formula we  iterate the points until we determine which points
are to be considered to belong to the set and which do not, (tested using
bailout and maxiter.)

I am not sure of the  coordinates where we start the iteration or the
order, (do we start  testing  (1, 0, 0),  (1, 0, 1), (1, 0, 2) ....?), or
top right hand corner of a bounded cube?? etc??

With multi threads we can allocate points to test to each thread to iterate
in parallel.



While we are iterating the formula, we are also updating our distance
estimation. The initial estimate for each point is 1.0, (TODO understand
how this maths works).

Upon completion we have a set of object points that  we consider to belong
to the formula set and an updated distance estimation for each point.


Then we ray march along  "pixel vectors" "pixel rays" ? originating from
the camera.

We are ray-marching to find the outer surfaces of objects within our Field
of View. There must also be  raymarching to find objects that will cast
shadow from outside the Field of View???.

For reflection we have to also bend the pixel-rays each time we hit a
reflective surface. I am not sure what is the initial step size is after
the reflection??

I have been assuming we are marching spheres,?????, but I have yet to
understand the maths of how we select object points for the ray marching
tolerance hit testing. (TODO understand the maths.)

SO Rob, I have still got some learning to do :)

**Comment by mancoast** [comment]
Thanks for the wealth of info!
I need some time to really think it through and understand.
The goal is to document the learning process.
