### ISSUE TITLE
Rework Client-Server functionality for render farms; Enhance Failure Recovery

### ISSUE THREAD

**Issue by Starmute** [buddhi1980/mandelbulber2#328]
Hello,

From my experience of using netrender it would seem advisable to add ways to kick clients out (i.e. if the computer is malfunctioning, or an undesired user connects):

(a) soft kick, just disconnects the client,
and (b) hard kick to disconnect and shut down the client's copy of Mandelbulber. Might be useful if you are temporarily using someone else's computer to render and do not want to inconvenience them.

**Comment by mancoast** [comment]
this is far beyond my understanding, i only trust @buddhi1980 to correctly implement.
I agree with the added value of dynamic render farm.

**Comment by zebastian** [comment]
Hi,
(a) soft kick will be effectless, since the client will reconnect right away
(b) hard kick
could be interesting. If the headless client hangs for some reason it can kicked and killed. A watchdog on the client could restart the Mandelbulber instance and reconnect. This could be a complete hard failover.
@buddhi1980 what do you think?

I can implement this, if we want this feature.

**Comment by mancoast** [comment]
@zebastian I misspoke earlier, you also have my support and trust to do this correctly.  AFANASY integration is one option.

**Comment by zebastian** [comment]
@mancoast never mind :)
Mandelbulber client <-> server communication is out of the render queues scope. In fact the render queue server manages a farm of mandelbulber servers. 
The structure is:
```
AFANASY
|
|------ SERVER 1
|         |-------- CLIENT 1-1
|         |-------- CLIENT 1-2
|         |-------- CLIENT 1-3
|
|------ SERVER 2
          |-------- CLIENT 2-1
          |-------- CLIENT 2-2
```

**Comment by zebastian** [comment]
@Starmute see latest commit, the kick button will be available with the next mandelbulber version
