### ISSUE TITLE
Nvidia Quadro K600 not available for OpenCL

### ISSUE THREAD

**Issue by lxegs** [buddhi1980/mandelbulber2#334]
OS : W10 x64 (v 1511)
mandelbulber version 2.12 alpha4

I have tried to enable OpenCL with my Quadro K600 but i have an error saying "there are no valid opencl plateforms in this system"

nvidia drivers are up to date

If i can help to debug something, i'm OK

thx

clement

**Comment by buddhi1980** [comment]
I wrote that you have recent video driver. But I want to confirm this. Please tell me which driver version do you have? 
W10 x64 (v 1511) is not recent that's why I'm asking. Actual Windows version is 1703.

By the way, have you ever tried any other application which use OpenCL? I would like to identify if it's software, driver or hardware related problem.

**Comment by buddhi1980** [comment]
Try to run http://www.geeks3d.com/20170327/gpu-caps-viewer-1-34-0-released/
to check if OpenCL works in your system.
On OpenCL tab you should see number of OpenCL platforms and all detailed information.

**Comment by lxegs** [comment]
my fault !

drivers were not @ latest version --> i have updated them and now all is OK

version drivers is 377.48 (previous was 376.16)

thx
