### ISSUE TITLE
enable netrender for opencl

### ISSUE THREAD

**Issue by zebastian** [buddhi1980/mandelbulber2#338]

**Comment by zebastian** [comment]
@buddhi1980 I am not sure where to put what to make this happen.
Is this a lot to do?

**Comment by buddhi1980** [comment]
NetRender for OpenCL is a very big topic. Actually out of scope.

**Comment by zebastian** [comment]
OK, thats what i thought.

**Comment by zebastian** [comment]
Since its quite big, i moved it to the 2.16 milestone

**Comment by mancoast** [comment]
@buddhi1980 @zebastian any thoughts here? I'll bet this one is a lot of work to get operational

**Comment by buddhi1980** [comment]
This is planned for 2.20. It was agreed with Mandelbulber community (FB group). I have asked users for development priorities, because there was a lot of demands from users. In 2.19 will be support for multiple gradients in Material editor. This release will focus on artists, not geeks :)
![image](https://user-images.githubusercontent.com/11696990/57632619-4daf5a00-75a2-11e9-9816-0bb18fd554ef.png)
