### ISSUE TITLE
Review CMake Refactor

### ISSUE THREAD

**Issue by mancoast** [buddhi1980/mandelbulber2#357]
qmake needs to be corrected
cmake needs to be corrected for linux
osx needs to be checked
cross compiler build scripts need to be reviewed
packaging scripts need to be reviewed

@lachs0r Do you have any comments on these TODO's?

REFERENCE:
https://github.com/buddhi1980/mandelbulber2/commit/25c5aacd37918c051a17f436ca555d30a4324357?diff=split

**Comment by zebastian** [comment]
everyone who is involved with this should take a look at their parts asap. Since the code base now is broken!

**Comment by buddhi1980** [comment]
@mancoast , all these TODO's should be done before merging this request. Pull request is a branch, so it's not a problem to add more commits and test them before merging.
Now you should focus on fixing all problems instead of listing TODOs. 
I'm away from home next few days, so I'm not able to help in correcting scrips. I will return to this topic in Thursday.

@lachs0r, your pull request is very good, but was merged when was not completed. It is not your fault.

**Comment by mancoast** [comment]
do Not be concerned, these updates are helpful and easy to accommodate. In the mean time, keep changes to cmakelists and roll back changes to codebase.

**Comment by mancoast** [comment]
symlinks and changes to system.cpp restored; changes contained to CMAKElists.txt; i do think this merge broke the build... it was already broken.

1.) qmake - unchanged! ==> does not reference CMAKElists.txt
2.) visual studio build - success
3.) cmake for linux *untested*
4.) cmake for osx *untested*
5.) cross compiler - does this reference CMAKElists.txt?  <==??
6.) packaging scripts - does this reference CMAKElists.txt?  <==??

I still need to test the some stuff, but the time is ripe to include contributions from others.
@lachs0r excellent work with the Linux package repositories!

**Comment by mancoast** [comment]
confirmed functional for linux and osx.
