### ISSUE TITLE
Program doesn't start because requires OpenCL.dll

### ISSUE THREAD

**Issue by mancoast** [buddhi1980/mandelbulber2#394]
This library should be optional in msvc build.

**Comment by buddhi1980** [comment]
@mancoast
All code is almost ready for dynamic loading of OpenCL.dll
In opencl_hardware.cpp:50 there is
```
#ifdef _WIN32
#ifndef _MSC_VER
	const std::wstring openclDll(L"OpenCL.dll");
	int err = clewInit(openclDll.c_str());
	if (err)
	{
		qCritical() << clewErrorString(err);
		missingOpenClDLL = true;
	}
#endif //   _MSC_VER
#endif
```
This code tries to open OpenCL.dll when WIN32 version is running. 
You have excluded it from _MSC_VER build, but I think it should work well.
To make it working you need to modify include_header_wrapper.hpp, because there is also excluded clew for msvc. 
Next think is to not link OpenCL library during compilation.

If you encounter any problems, let me know.

**Comment by mancoast** [comment]
clew does not operate with msvc.  I have tried many things: https://forums.khronos.org/showthread.php/11392-Yet-another-discussion-about-OpenCL-dll

I will build our own OpenCL.dll and distribute it along with the application. The license permits us distribute it freely.  https://www.khronos.org/registry/cl/specs/opencl-icd-1.2.11.0.tgz

**Comment by buddhi1980** [comment]
OK. We can try to distribute with application. As I have just read, it's just helper library which calls functions ICD. It should work.

**Comment by mancoast** [comment]
confirmed function in vista hyper-vm
