### ISSUE TITLE
OpenCL takes too much GPU priority

### ISSUE THREAD

**Issue by raisingw** [buddhi1980/mandelbulber2#417]
Rendering anything using OpenCL currently brings my system to a crawl, graphically speaking. Anything elsewhere only progresses once a square of fractal image has been rendered and Mandelbulber moves onto the next one. If the render is especially complex my system feels like it has frozen completely as I can't interact with anything until the next square is done.

Is there any way to reduce the priority of the GPU processing? Admittedly I don't even know if OpenCL processes work in this way but it makes GPU rendering near unusable for me for more complex images.

Using Ubuntu 16.04 and 17.10 (Unity 7 and GNOME 3) with a GeForce GTX 750 Ti (need a new one!), driver version 384.90. Current git build of Mandelbulber.

**Comment by mancoast** [comment]
Welcome @raisingw,

We greatly appreciate your feedback and I strongly agree with your scenario.
@buddhi1980 is it possible to allocate %95 of GPU, [honestly, opencl is well beyond my knowledge].
This would enable OS inter-operation concurrently with the mandelbulber2 system.
Perhaps we can simultaneously solve this issue and the TDR issue with windows?

Thanks,
coast

**Comment by TasMania17** [comment]
Hi raisingw, 
What is the output of the command  #clinfo 
You should be able to paste it here.

**Comment by buddhi1980** [comment]
Graphics drivers have no capability to set priorities for tasks. In general they are not so well prepared for multitasking.
It's also not possible to reduce allocation of GPU. Actually there is used CL_KERNEL_PREFERRED_WORK_GROUP_SIZE_MULTIPLE to run the program with optimal global_work_size. If will be used lower size, rendering will be slower, but you will not see difference in multitasking. It's because rendering of each pixel will still take the same time, but amount of simultaneously rendered pixel will be lower. For that time GPU is busy.
 So in general as fast the enqueued work is executed as the system is more responsive. 
Calculation of 3D fractals is computation extensive, so it's not possible to get quick calculation. 
This is big disadvantage of computation on GPUs. 
If you want to have system well running with background GPU computation, you need to have second graphics card which will be used only for computation.

**Comment by raisingw** [comment]
Thanks for the responses everyone, especially @buddhi1980 for the detailed explanation! If it truly is the only solution to the issue, I guess I'll have to think about investing in a second GPU if I want to get serious with this but also have my computer remain in a usable state!
