### ISSUE TITLE
mesh export: crash on 60000 resolution

### ISSUE THREAD

**Issue by mancoast** [buddhi1980/mandelbulber2#433]
when trying to queue up very large mesh, system always crashes due to low memory.
Is it possible to rework with larger resolution support? (i am testing with 60k)

**Comment by zebastian** [comment]
@mancoast That resolution is crazy
On my i7 it takes roughly 0,00000125 seconds per voxel (default mandelbulb with -1-1-1-111 limits)
This is ~10secs for 200x200x200
and 260.000.000secs for 60000x60000x60000
which is about 8 and a half years!

BTW: even if you can handle to render so long the file would be huge, and every program loading that file would blow immediately.
IMHO: anything more than say 10000^3 is not handleable in any way.

**Comment by zebastian** [comment]
On my PC the crash also happens, 
We should try-catch and display an error popup on bad alloc like the bad allocation handler for the cimage.

**Comment by mancoast** [comment]
I can export at 15k in about 24hrs.  I cannot get the system to operate above 15k (have 64gb of ram).  I am curious if its possible to enable unlimited resolution for the mesh.

**Comment by mancoast** [comment]
I am exploring map options for VR based unreal engine stuff.  The color
export with the voxels makes these awesome dream worlds with the vive.

**Comment by zebastian** [comment]
@mancoast I added error handling so now the program wont crash on bad alloc but show a message.
The general problem is not the buffers of the slicing algorithm (voxelBuffer, ...), since the [polygons, indices] require much more memory than that (A test showed a ratio of 1 / 10, but the gap increases with growing volume size).
It only crashes on alloc of voxelBuffer, ... because this is the first occurence of heavy memory requirement and the  [polygons, indices] only require more memory incrementally and it takes longer the get out of memory there, but these buffers are the real bottleneck.
IMHO There is no feasable way to make these buffers streamable, so the problem persists: For huge mesh volumes to render you need a LOT of mem.

You could try to enable swapping for this instance, sincce the allocated memory is not accessed too much, this might perform quite OK.
