### ISSUE TITLE
feature request - more than one directional light

### ISSUE THREAD

**Issue by taurus66** [buddhi1980/mandelbulber2#482]
I seldomly utter new features, as I am mostly happy with the given options. But within animations, when main light source is not assigned to the camera, I often miss the opportunity to place one or two fill lights. Positional light sources are barely an option, because they are strongly dependent to their position - too bright when near and almost invisible in the distance. 
It would be great to switch custom lights between directional and positional light, as it is usual in many 3d applications including m3d, Blender and many more.
Cheers taurus

**Comment by buddhi1980** [comment]
It is very good idea.
I have in future plans to implement more options for light sources. There should be possible to define them as you mention and also as a user defined cone. Another thing is an option to connect them to the camera and use relative distance and angle.
I cannot tell you when it would be implemented because the list of TODOs is so long.

**Comment by taurus66** [comment]
Thanks in advance. Especially the connection to camera is no option for me, as I don't like wandering shadows in animations. That's the reason why I sometimes move through the dark or ambient lit areas...

**Comment by mclarekin** [comment]
i think this is resolved in v2.25
