### ISSUE TITLE
Render queue crashes program

### ISSUE THREAD

**Issue by mclarekin** [buddhi1980/mandelbulber2#493]
step 1,  ascertain what steps are required to reproduce
current status, crashed on first attempt to render image, OK on subsequent renders.

**Comment by mclarekin** [comment]
Ubuntu, load program, added two files from a folder to the queue, hit render queue = frozen screen (and eventually could not end task and had to restart computer.)
attached data
[queue cr.txt](https://github.com/buddhi1980/mandelbulber2/files/2105642/queue.cr.txt)

**Comment by mclarekin** [comment]
SIGSEV

Signal name : | SIGSEGV
-- | --
Signal meaning : | Segmentation fault

**Comment by buddhi1980** [comment]
I cannot reproduce this problem.

**Comment by michaelsteffen1982** [comment]
Maybe a different problem, but MB on my laptop (which has only 2g of ram) some days ago also crashed with a Seg-fault when I tried to render a very large picture (on CPU, no OCL). But only a crash of MB, no complete freeze. I did no further test as I use it not often.

My PC sometimes freezes completely when I render large pics with OCL and doing something with Firefox at the same time...then it sometimes freezes completely, I have to restart the whole PC, no taskmanager or softreset is possible anymore. Is it somehow possible maybe to 'catch' these situations/freezes anyhow so that the taskmanager would still be reachable / improve multitasking? Or is it a general problem of OpenCL?

**Comment by mclarekin** [comment]
i can still reproduce the my queue problem
[Backtrace_1.txt](https://github.com/buddhi1980/mandelbulber2/files/2211926/Backtrace_1.txt)
Currently not freezing, but crashing out of program.

**Comment by buddhi1980** [comment]
What you mean by crashing? How the program behave? In the backtrace there is no evidence of any crash.

**Comment by mclarekin** [comment]
I try and render queue = program closes.  I think it can also become
unresponsive

I  will check if i can reproduce in windows version, later on.

On Fri, Jul 20, 2018 at 9:13 PM, Krzysztof Marczak <notifications@github.com

**Comment by mclarekin** [comment]
Cannot currently reproduce on Windows. I will continue to monitor this issue


Notes to me on test procedure:.
Fresh install Mandelbulber
view - show queue dock
relocate queue dock
check  queue list and there are no files pending
retrieved  toolbar standard presets
use add_file to select two toolbar standard presets
rendered queue , ALL GOOD

**Comment by zebastian** [comment]
@michaelsteffen1982 please dont piggyback unrelated issues, since your issue has not been recognized in this issue.
Your problem seems to be an out of memory problem, with 2GB of RAM that can happen quite fast. We are doing only rudimentary memory check before memory allocation, So in some edge cases (enough ram for checked allocation, not enough ram for unchecked) you might just get a crash.

If you still get this problem, please reopen another issue. sorry for the late answer.

**Comment by zebastian** [comment]
@mclarekin please reopen, when issue is happening again.
