### ISSUE TITLE
formula research

### ISSUE THREAD

**Issue by mclarekin** [buddhi1980/mandelbulber2#498]
http://www.fractalforums.com/amazing-box-amazing-surf-and-variations/platonic-dimensions/

**Comment by TasMania17** [comment]
This is needed IMHO. Suggested names - 'sandbox' or 'blackboard'. After the OpenCL is working this could be next. 
I don't think the fractal formula maths heads will use Mandelbulber unless there is somewhere to experiment.
I'm familiar with a program where a bad formula just crashes the program. It's not a big deal because it's just a 'plugin' and the main program is still running. I don't know enough about how MDB2 works but is it possible to run a sandbox in a protected environment? 
I thought of a 'blank fractal formula' where users could paste-in their own formulas. Could this be possible on MDB2

**Comment by mclarekin** [comment]
Tas, Old ManderbulberV1.21 had a custom formula section and eventually this may be implemented in V2.  And , yes, i have yet to get any "maths head" to code formulas in the program.

For now, a user needs to be able to edit and compile the program (which has never been easier.) I have some Testing Formulas at the bottom of the formula list where I can play around, and then when I am happy I just rename the formula and copy and paste.  The chance of a formula crashing the program is now very small, but I do sometimes accidentally create very long iterations that can appear to freeze the computer, and have to end process and reinstall. These days crashes are more likely be related to the type and model of  GPU .

There is still a lot of formulas to be coded and tested, more than I will ever be able to do. The links above are to remind me of some of them.  I once had a huge list bookmarked, but lost it all when updating Ubuntu.

**Comment by mclarekin** [comment]
evaluate a  Mandelbulb 4 mod1
