### ISSUE TITLE
Enable infinite zoom

### ISSUE THREAD

**Issue by ghost** [buddhi1980/mandelbulber2#510]
In the current state, the ability to zoom in on the fractal is limited at the limits of the double and single data types, infinite resolution is lost due to significant digits. 

Consider the Menger Sponge. Is it possible to rework the iteration functions and the entire algorithm to maintain infinite resolution using single precision data types?  

This issue surfaces for example files rendered on GPU, but designed on cpu with the zoom only supported by the double precision of the cpu.

**Comment by zebastian** [comment]
IMHO: the maths for "calculating a point based on a known point close by" cannot be applied, since there is no common maths for calculating the iterative difference for a fractal. Even if we could find a way to compute it for a fractal it will not be applicable / portable for other fractals.
The mandelbulber fractals with the thousands of different settings are just too complex for this approach.
Though the superfractalthing maths may be applicable to the 3d mandelbulb, i am not a mathematician! :D
Every approach for working with finer doubles (quadruple and more) will sacrifice too much compute power.
I see no (moderate) way for infinite zoom :/

**Comment by zebastian** [comment]
This made me thinking, maybe there is still more to the SUPERFRACTALTHING-idea applicable for mandelbulber then i first thought.
We could calculate a couple of good DE base points.
From these base points we could find a generalized taylor approximation to points nearby which should be faster to calculate with only small delta values inside the approximation.
This could be used to
- calculate faster in general
- calculate base points with infinite (high) accuracy in first pass, calculate other points with float accuracy from these base points in second pass.

The maths are beyond my abilities and i dont know how much:
- the error
- the savings
 of such an approximation will be.

**Comment by mancoast** [comment]
I have read this paper about new types constructed from single precision floats: http://andrewthall.org/papers/df64_qf128.pdf

I am curious if we can creatively implement something like this for GPU.
