### ISSUE TITLE
new difference in openCL and c++ images

### ISSUE THREAD

**Issue by mclarekin** [buddhi1980/mandelbulber2#526]
There is a problem, visible difference between c++ and openCL.

```
# Mandelbulber settings file
# version 2.15
# only modified parameters
[main_parameters]
ambient_occlusion 1.5;
ambient_occlusion_enabled true;
ambient_occlusion_mode 1;
ambient_occlusion_quality 3;
camera -0.05315592620830209 -4.11106993601906 -3.973512311437726;
camera_distance_to_target 0.02444201555796206;
camera_rotation 6.514482043800476 66.56693953642188 -147.462072357811;
camera_top -0.6221426217925363 0.7074898218953994 -0.3352561857200033;
DE_factor 0.78125;
detail_level 4;
flight_last_to_render 0;
formula_1 64;
formula_2 1063;
formula_iterations_1 4;
fov 0.3;
hybrid_fractal_enable true;
image_height 540;
image_proportion 4;
image_width 960;
keyframe_last_to_render 0;
main_light_alpha -62.1;
main_light_beta 21.12;
mat1_coloring_palette_size 5;
mat1_coloring_random_seed 443410;
mat1_fresnel_reflectance true;
mat1_is_defined true;
mat1_reflectance 1;
mat1_specular_metallic_roughness 1;
mat1_surface_color_palette 00697f ff9317 4aff57 1f2ded 684adc;
mat1_transparency_index_of_refraction 3;
perspective_type fish_eye;
raytraced_reflections true;
reflections_max 2;
target -0.05425870660852804 -4.101412659496996 -3.951086143461433;
view_distance_max 800.2108774380708;
[fractal_1]
mandelbox_scale 1.1;
transf_addition_constant_111 1.4 1.4 1;
transf_rotation 2 8 -10;
[fractal_2]
transf_function_enabledAx false;
transf_function_enabledAx_false true;
transf_function_enabledx false;
transf_function_enabledy false;
transf_offset_111 2 1.9 1.8;
```

**Comment by mclarekin** [comment]
A problem with normal vector calculations caused by increased detail level (in low resolution). Then all shaders and raytraced reflections are calculated wrong

**Comment by buddhi1980** [comment]
I have eliminated some of differences between CPU and GPU calculation.

But for this case the problem is very special. It needed about 150 fractal iterations in some places. But calculation of normal vectors needs sometimes 5 times more iterations. On fractal tabs there is set "stop at iteration" = 250, so some calculations of normal vectors (after 250 iteration) are empty. If you change this parameter to 2000 then the fractal in CPU mode looks all right.
In OpenCL mode this problem was not visible because fractal sequence is limited to 250 iteration (limitation of memory for constants). After 250 iteration there is repeated always the latest used formula slot.

**Comment by mclarekin** [comment]
thanks for the interesting explanation on calculation of normal vectors

**Comment by buddhi1980** [comment]
There is no visual difference between CPU and GPU. Can you send image to show how it looks on your PC?

**Comment by buddhi1980** [comment]
This fractal in general behaves very weird. Distance field is very distorted. It causes bad calculation of surface normal vectors.

**Comment by buddhi1980** [comment]
I have found the problem and fixed. Now this fractal looks all right in CPU and OpenCL mode.
It should not introduce any backward compatibility problems.

**Comment by mclarekin** [comment]
looks good!
