### ISSUE TITLE
cli issue with "touching"/upgrading  of old mandelbubler v1 f

### ISSUE THREAD

**Issue by zebastian** [buddhi1980/mandelbulber2#548]
cli "touching"/upgrading  of old mandelbubler v1 files causes resulting file to contain dummy data

**Comment by buddhi1980** [comment]
I think conversion of many settings from v1 to v2 should not be done in batch process. From my experience there is needed to open settings in Mandelbulber v1.21 and see how the fractal look like. Then import in v2 and compare. I'm many cases there are needed manual adjustments, because rendering engine evolved a lot since 1.21. I know that it takes time, but in other case we will get a lot of rubbish settings in examples.

**Comment by mclarekin** [comment]
I  would not spend time on converting, and think we can just present them
as V1.#  files for now. Maybe in the distant future they could be converted.

**Comment by zebastian** [comment]
@buddhi1980 I see, probably better to remove this again then. I will take care.

@mclarekin I will make the raw zip available at mandelbulber.org
I will add a "chosen" subset of settings to the example settings folder. 
IMHO: better not add the raw settings / old v1 settings to the examples folder to not confuse the users with incompatible files.

**Comment by mclarekin** [comment]
sounds good
