### ISSUE TITLE
Disable DoF on black frames

### ISSUE THREAD

**Issue by paigan0** [buddhi1980/mandelbulber2#638]
##### Detailed description

When using DoF, and encountering black frames that are collisions, can DoF be disabled for those frames? Rendering DoF for black frames can take expontentially more rendering time, for no result. Related, for frames that have a very high DoF effect, the render can take hours just to produce a completely blurred image. That might be too hard to do anything about. But completely black frames are detected by the Validation procedure, so they could hypothetically also be ignored for DOF calculations.

Is this something that could be implemented without too much chaos? I appreciate the awesome support!

**Comment by buddhi1980** [comment]
In commit https://github.com/buddhi1980/mandelbulber2/commit/4013b73a1a11f958263395418bd4f4ed41d0b6ea I added elimination of calculation DOF for pixels where distance is almost zero. It should eliminate described problem in most of cases.
I hesitate to use information about collisions, because in many cases these frames are still properly rendered (object can be just behind the camera)
To reduce calculation maximum time for DOF you can reduce maximum radius of DOF effect (option in DOF groupbox). Default is 250, but in most of cases 50 will be enough (will be 25 times faster in places with very strong blur)
