### ISSUE TITLE
camera rotation problem

### ISSUE THREAD

**Issue by mclarekin** [buddhi1980/mandelbulber2#67]
Set up looking along the y axis all rotations angles = 0.0 and set Rotation step to 90.0.

Now use the up arrow (pitch) rotation,   I get

one rotation 	      	0, -90, 0
two rotations			-180, 0, -180
three rotations			63.43494882292206, -	90,  63.43494882292206
four rotations 			-116.5650511770779, 0 , -116.5650511770779

and you can not reverse the action to get back to the original 0, 0, 0
(it does not have to be 90 degrees, but it is easier to see the weirdness.)

**Comment by buddhi1980** [comment]
Which rotation mode have you used for this test: "Fixed roll angle" or "Straight rotation"?
If you use "Fixed roll angle" and when camera is in vertical orientation (looking 90 degrees up or down), then yaw rotation is mathematically undefined. It's because yaw and roll axes are overlapped in this situation.
When camera is going to be in vertical orientation you should always use "Straight rotation" mode, which uses only rotations based on local camera coordinate system. In this mode camera will always return to the same rotation if you repeat sequence backwards.

**Comment by mclarekin** [comment]
was using "fixed roll angle"  so  that explains it so issue solved.
