### ISSUE TITLE
OpenCL only running at 256 workgroup

### ISSUE THREAD

**Issue by artBoffin** [buddhi1980/mandelbulber2#670]
##### System information (version)

- mandelbulber2 => v2 2.18-1
- Operating System / Platform => Linux Mint / Windows 10
- Compiler => NA

##### Detailed description

OpenCL render only running at 256 workgroup size on complicated fractal with latest drivers on both Linux and Windows with dual RTX 2080 TI cards 

When I run the benchmark_gpu fractal I get 384 size, 6.4 seconds

**Comment by buddhi1980** [comment]
It is normal that workgroup size is only 256 with complicated fractals, because a lot of GPU resources is needed. Even the best GPUs have too low number of registers to handle such a big code. They are prepared for massively parallelized execution of small code. See these numbers for GTX 1060
```
  Max work group size                             1024
  Preferred work group size multiple              32
  Warp size (NV)                                  32
  Global memory size                              6373572608 (5.936GiB)
  Max memory allocation                           1593393152 (1.484GiB)
  Local memory size                               49152 (48KiB)
  Registers per block (NV)                        65536
  Max number of constant args                     9
  Max constant buffer size                        65536 (64KiB)
  Max size of kernel argument                     4352 (4.25KiB)
```
Some numbers are almost like on very old C64 computers :)

Size of formula code has the biggest impact here, because fractal calculation is called in many places in the code.

**Comment by buddhi1980** [comment]
About speed of your dual 2080. It is very good result. On 1050 + 1060 it takes 30s (workgroup size is also 384)
